### ISSUE TITLE
running `conpot -f --temp_dir <custom dir> --template default` gives error while running

### ISSUE THREAD

**Issue by KorpoleRithika0x1** [d4emonsAVI/conpot#9]
Don't attach images of terminals but provide the text.
```
 --template default
WARNING:scapy.loading:Cannot read wireshark manuf database
WARNING:scapy.runtime:No route found for IPv6 destination :: (no default route?)

                       _
   ___ ___ ___ ___ ___| |_
  |  _| . |   | . | . |  _|
  |___|___|_|_|  _|___|_|
              |_|

  Version 0.6.0
  MushMush Foundation

WARNING:root:--force option specified. Using testing configuration
2023-06-14 17:54:43,115 --force option specified. Using testing configuration
2023-06-14 17:54:43,116 Starting Conpot using template: /usr/local/lib/python3.6/dist-packages/conpot/templates/default
2023-06-14 17:54:43,116 Starting Conpot using configuration found in: /usr/local/lib/python3.6/dist-packages/conpot/testing.cfg
WARNING:conpot.core.virtual_fs:Using default FS path. tar:///usr/local/lib/python3.6/dist-packages/conpot/data.tar
2023-06-14 17:54:43,120 Using default FS path. tar:///usr/local/lib/python3.6/dist-packages/conpot/data.tar
2023-06-14 17:54:43,121 Initializing Virtual File System at /home/adhd/job/conpot/ConpotTempFS/__conpot__4yjlk5s5. Source specified : tar:///usr/local/lib/python3.6/dist-packages/conpot/data.tar
 Please wait while the system copies all specified files
2023-06-14 17:54:43,245 Fetched 69.46.1.81 as external ip.
2023-06-14 17:54:43,252 Conpot modbus initialized
2023-06-14 17:54:43,252 Found and enabled ('modbus', <conpot.protocols.modbus.modbus_server.ModbusServer object at 0x7f274b6416d8>) protocol.
2023-06-14 17:54:43,256 Conpot S7Comm initialized
2023-06-14 17:54:43,256 Found and enabled ('s7comm', <conpot.protocols.s7comm.s7_server.S7Server object at 0x7f274b5ee908>) protocol.
2023-06-14 17:54:43,257 Found and enabled ('http', <conpot.protocols.http.web_server.HTTPServer object at 0x7f274b5ee2e8>) protocol.
2023-06-14 17:54:43,258 Found and enabled ('snmp', <conpot.protocols.snmp.snmp_server.SNMPServer object at 0x7f274b5ee898>) protocol.
2023-06-14 17:54:43,259 Conpot Bacnet initialized using the /usr/local/lib/python3.6/dist-packages/conpot/templates/default/bacnet/bacnet.xml template.
2023-06-14 17:54:43,260 Found and enabled ('bacnet', <conpot.protocols.bacnet.bacnet_server.BacnetServer object at 0x7f274b5ee470>) protocol.
2023-06-14 17:54:43,260 IPMI BMC initialized.
2023-06-14 17:54:43,261 Conpot IPMI initialized using /usr/local/lib/python3.6/dist-packages/conpot/templates/default/ipmi/ipmi.xml template
2023-06-14 17:54:43,261 Found and enabled ('ipmi', <conpot.protocols.ipmi.ipmi_server.IpmiServer object at 0x7f274ab17940>) protocol.
2023-06-14 17:54:43,262 Class    22/0x0016, Instance   1, Attribute     1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2023-06-14 17:54:43,262 Class    22/0x0016, Instance   1, Attribute     2 <== [{'class': 22}, {'instance': 1}, {'attribute': 2}]
2023-06-14 17:54:43,262 Class    22/0x0016, Instance   1, Attribute     1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2023-06-14 17:54:43,263 Class    22/0x0016, Instance   1, Attribute     3 <== [{'class': 22}, {'instance': 1}, {'attribute': 3}]
2023-06-14 17:54:43,263 Class    22/0x0016, Instance   1, Attribute     1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2023-06-14 17:54:43,264 Class    22/0x0016, Instance   1, Attribute     2 <== [{'class': 22}, {'instance': 1}, {'attribute': 2}]
2023-06-14 17:54:43,264 Found and enabled ('enip', <conpot.protocols.enip.enip_server.EnipServer object at 0x7f274ab17ac8>) protocol.
2023-06-14 17:54:43,266 Creating persistent data store for protocol: ftp
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fs/osfs.py", line 315, in makedir
    os.mkdir(sys_path, mode)
PermissionError: [Errno 13] Permission denied: b'/usr/local/lib/python3.6/dist-packages/conpot/tests/data/data_temp_fs/ftp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conpot", line 455, in <module>
    main()
  File "/usr/local/bin/conpot", line 375, in main
    server = server_class(protocol_template, root_template_directory, args)
  File "/usr/local/lib/python3.6/dist-packages/conpot/core/protocol_wrapper.py", line 27, in __init__
    self.wrapped = cls(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/conpot/protocols/ftp/ftp_server.py", line 225, in __init__
    self.handler.config = FTPConfig(self.template)
  File "/usr/local/lib/python3.6/dist-packages/conpot/protocols/ftp/ftp_server.py", line 103, in __init__
    self._init_fs()        # Initialize FTP file system.
  File "/usr/local/lib/python3.6/dist-packages/conpot/protocols/ftp/ftp_server.py", line 117, in _init_fs
    perms=self.default_perms)
  File "/usr/local/lib/python3.6/dist-packages/conpot/core/__init__.py", line 55, in add_protocol
    return virtualFS.add_protocol(protocol_name, data_fs_subdir, vfs_dst_path, src_path, owner_uid, group_gid, perms)
  File "/usr/local/lib/python3.6/dist-packages/conpot/core/virtual_fs.py", line 118, in add_protocol
    sub_data_fs = self.data_fs.makedir(path=data_fs_subdir)
  File "/usr/local/lib/python3.6/dist-packages/fs/osfs.py", line 323, in makedir
    return self.opendir(_path)
  File "/usr/local/lib/python3.6/dist-packages/fs/error_tools.py", line 91, in __exit__
    reraise(fserror, fserror(self._path, exc=exc_value), traceback)
  File "/home/adhd/.local/lib/python3.6/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/fs/osfs.py", line 315, in makedir
    os.mkdir(sys_path, mode)
fs.errors.PermissionDenied: permission denied
2023-06-14 17:54:43,292 Modbus server started on: ('0.0.0.0', 5020)
2023-06-14 17:54:43,293 S7Comm server started on: ('0.0.0.0', 10201)
2023-06-14 17:54:43,293 HTTP server started on: ('0.0.0.0', 8800)
2023-06-14 17:54:43,487 SNMP server started on: ('0.0.0.0', 16100)
2023-06-14 17:54:43,489 Bacnet server started on: ('0.0.0.0', 47808)
2023-06-14 17:54:43,489 IPMI server started on: ('0.0.0.0', 6230)
2023-06-14 17:54:43,489 handle server PID [  976] running on ('0.0.0.0', 44818)
2023-06-14 17:54:43,490 handle server PID [  976] responding to external done/disable signal in object 139806695164328
2023-06-14 17:54:43,490 Serving TCP/IP:     1, UDP/IP:     0, w/ latency:   0.100s, timeout:   0.200s (w/NO idle service)

```

**Comment by GryphonInfoSec** [comment]
Try using the new install instructions in the readme.  I just did a fresh install from source and was not able to duplicate.
